---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app forgejo-runner
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: forgejo
      namespace: gitea
  values:
    controllers:
      *app :
        type: statefulset
        replicas: 2

        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

        statefulset:
          volumeClaimTemplates:
            - name: data
              globalMounts:
                - path: /data
              accessMode: "ReadWriteOnce"
              size: 1Gi

        initContainers:
          register:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 11.3.1@sha256:287433414b987b89896399683034818db198079053d84ca473aadb06ebad8b9f
            command:
              - "sh"
              - "-c"
              - >
                if [ ! -f /data/.runner ]; then
                  echo "Registering runner...";
                  forgejo-runner register --no-interactive \
                    --token $(RUNNER_TOKEN) \
                    --name $(RUNNER_NAME) \
                    --instance $(FORGEJO_INSTANCE_URL) \
                    --labels "$(LABELS)";
                else
                  echo "Runner already registered, skipping.";
                fi
            env:
              FORGEJO_INSTANCE_URL: http://forgejo-http.gitea.svc.cluster.local:3000
              LABELS: "ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-latest"
            envFrom:
              - secretRef:
                  name: forgejo-runner-secret
        containers:
          daemon:
            image:
              repository: docker
              tag: 28.5.2-dind@sha256:2a232a42256f70d78e3cc5d2b5d6b3276710a0de0596c145f627ecfae90282ac
            securityContext:
              privileged: true
            env:
              - name: DOCKER_TLS_CERTDIR
                value: /certs
          app:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 11.3.1@sha256:287433414b987b89896399683034818db198079053d84ca473aadb06ebad8b9f
            command:
              - "sh"
              - "-c"
              - "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; forgejo-runner --config /config/config.yaml daemon"
            env:
              - name: DOCKER_HOST
                value: tcp://localhost:2376
              - name: DOCKER_CERT_PATH
                value: /certs/client
              - name: DOCKER_TLS_VERIFY
                value: "1"
        annotations:
          reloader.stakater.com/auto: "true"

    service:
      app:
        controller: *app
        ports:
          http:
            port: 45315

    persistence:
      config:
        type: configMap
        name: forgejo-runner-configmap
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true

      certs:
        type: emptyDir
      cache:
        type: emptyDir
