---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-runner
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: forgejo-runner
  components: []
  interval: 1h
  path: ./kubernetes/apps/gitea/forgejo-runner/app
  postBuild:
    substitute:
      APP: forgejo-runner
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: gitea
  timeout: 5m
