---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
components:
  - ../../components/common
resources:
  - ./forgejo/ks.yaml
  - ./forgejo-runner/ks.yaml
  - ./renovate/ks.yaml
