---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./claim-r0.yaml
  - ./minio-r.yaml
  #- ./claim.yaml
  #- ./minio.yaml
  # - ./nfs.yaml
  # - ./r2.yaml
