---
# yaml-language-server: $schema=https://my-kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: neko
spec:
  components:
    - ../../../../components/volsync
  interval: 1h
  path: ./kubernetes/apps/default/neko/app
  postBuild:
    substitute:
      APP: neko
      VOLSYNC_CAPACITY: 15Gi
      #SUBDOMAIN: movienight
      #VOLSYNC_SCHEDULE: "0 */3 * * *" # Every 3hrs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
