apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:j9nS8xuDZSDrq/XhYQTke6mCEAH61m+0WEUr5Sz6N1GKhdb6ZkQDWQ==,iv:2EPznkwdqkJOPQK6g5zIQoDLE/XyrTqvyCwoXemoGt4=,tag:v7sezL5BZelEoFOXinH9XA==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdUFCQkZKQld4SGRlek1k
        ZUp0NFIvRHZHcy9Nd1JhTjlrc2I3akJwZXd3CkliQ3NwTWpGOGZ5ckU5b0VEMThx
        eEhVVlpnajFmallQODJHdGJiM3lCYkkKLS0tIEFQRzljYmF1dWVOTEdWcGpDR0pG
        VjVVeTBKQlFuQ2x4cXI3OUc0T0t3WHMK3CNHR7gE6oin13Z5GNj9ZusXppe7tTkI
        xg4aeVhBq3vkTXDOrbG+67nJ+96RX8YijTbIZ7DhVOVAFP7W+cQgKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:17:05Z"
  mac: ENC[AES256_GCM,data:hNqGpOmCVglakuOSaf0Hszkug+Vpj9eGnrJ+x6WLuqz1TbaDwHDoh9Cnlb0kUcvM22xxFTY+PsNb/fLMoy2YQFY2BHfvNPDo9FmfSZOYhmcwkITzl/2B28oa4T5N/WX5x5IGeKPMg3hPGFtfiPCI4eJjyhMTTCCGiv9HiII8up0=,iv:kl6OL4OmAP7ruzkfOSe2e3oh9dDtWypRVB/eEh2OAjE=,tag:DJU82G5BITv2bEwliQy0hg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
