apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:xE/PV/M5unP44+a19I2R4Sy+OtU1KqymUrXYc17YRGaB3KLE1jTlsA==,iv:NF5JZnQO9Hlwpf9pXEZ8d1pegBHUj5N2iErBmE9QQHs=,tag:OOO72LInnfd9xYGGEoLDdQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dWRsenlPWFNWVjV6d2Nz
        YnZOc1B2UUxpdlI0c2g0ZTNZcDFWdHdoUmgwCmlxRnd4aTJwWFp4TitNVnFhbTdk
        Z0NBaTRtc0RnVWZCbFB3RzhXL1JJTTAKLS0tIC9MVjRKUWcrdVJ0MEE5WHV0MEkr
        ek5aSVk5VjgxOFZySytVM3BnOVRVdzQKkz2xg5nJsxDJHedCkDs6waKSZ/gi2Ds+
        kij5WstULgcs2OisP/C0WeQ9uHw+95bYYD/0pjwINajTU6MAO66aKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T14:28:49Z"
  mac: ENC[AES256_GCM,data:hD6z8x31wsYN8CpNWb5xDQN4eitWJN4h7CVDS24bLh36XYdpu4DZd66nPOKRBW29lNC0sAXesptp4yjd+CH8SA1imkSOWj7xjifPI5jEwLfxHMuw42zkoJKlZhhISmWBCjlsUxFL03lGsG+cz1gS4MaGBifxxXiLwb5FtSDLmnk=,iv:LVU61xie3EoaHDqVcbIxz6HmOMudpNztKp/Cf33zh1g=,tag:WCCA5N6rWtNh9mu5a7kgig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
