apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:EItDGEESh+NlzSnapCbdKSWW4FwSVpQC8wi7aCyNLGmXB5ctxBPQ8Q==,iv:RA67qz8Mc0ogKGWBJzCfUP3qEx32jfBbNXWYpj4j4F8=,tag:jjcrPwXlAM6kJMOiZBqOhQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVzNaa0RoQlZHSTJOeUpv
        T3llZlgwVXBNa3FpWTJzNSt3L09IUkVUQ0N3CkxxWXJsMThuRVNrZ1BzTEZJNHhw
        aGpzUVhIR0VuUzdwY1dzQlVna3ZGckEKLS0tIGExMkVueUZhdzVaOGlsc1M4V05L
        RW1zVTlaMTVBRDRoUzVHMzBnWDZyNDQKu8LR8ZZXEj8+IMo/SDpv5rjB4KGjvKTJ
        h3jP+Rl87OCkrGLgAD6RtuhRjhly6UqZKJeWLZHKItppin6qp9yvEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T20:48:26Z"
  mac: ENC[AES256_GCM,data:LoZwMDZHDZZnSDgBBlj0yOxsKW5/hZSw+5E7XkSAxuLPmmrAFL6rvYUrPseM4KQgA9wHmknignlFGfjyz81sEliqzxj5KwAZQeGK/APMeBiOxgtTfIuIo3zkUy9G6idj1q4QlX5LPOwBMi/vyoVeCS6BbWnqBJpxjbC75bFtRDw=,iv:kXArTKARKnNKkE2LIEXdLeY/9gtLHziiJ7q+kmiRgdA=,tag:9uKOf1yXddxM9hWJJlNM8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
