apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:t12V0SZJEv8gA6vMDmp5Zxn2ThVnBPEk+fNxx3q3UuWDa05dPBm2fw==,iv:mMBYgUpSVJBV9PCUbsjdgFUr5MBKQRJMxo0WeyfvPDc=,tag:WZS+0/FM4wieX2eu2iCU1Q==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSWExSURvZU56a0g5aHN1
        c1JGRXdFWkNveEpmTU5YcnJJSzFCMzQrenpFCjVSdExuWTVvNlR3MmVOSEU1Vyti
        c3E3NFpSZDlYTlNxYlUxRnYrM29GVFkKLS0tIFBDc1ZJRjhyZTg1bzB6ZlpIZ01a
        dmQ3ZDRValU0NjI2bHpKbU9aSTVZRXMKc0z0sR8YSB6jvW7CdWgUDO4FoBxUzlXY
        RZ5gvJMYBEafROseFoe09D1csT5MjVQ4HfIoMOuQcakcKS7O1EjnlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:54:38Z"
  mac: ENC[AES256_GCM,data:U5OtZQkdAa4Z/2lCLD0QjbjOEBGeY/mlcUwbmfurw80rr4ETRVASdh0vAStJWxS8NIVeNa8uj+6wcgB+HGDnkm8UKm20OZwlQA9muwjA5WM3lxUyLsAyT/JDRyauyZ6eDCzDFxyw5c0A6bbhDSpsJlz9B7j+xwvQvB6oMDYpe3c=,iv:jxc2hktWkYwL+dw19igKnsQOaF0E+XLCYrTQrintVOw=,tag:MNys4YrOynRuM6aeDMKkmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
