apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:fP7l3adNEUtMPbhSEU4sKGT94gy9W2KJRquU+Hwk4qSpa6QUGvM60w==,iv:Z4NfgBScG+qJg0Jc/Mfjzlpsqtuqn96e5WPmYRO2hdA=,tag:IHy5tayiuqTnUsKdw00X2Q==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRjkrVFNLblBVZDFNbUNt
        SUJIMGNXaG1CdHhuNUZEWE54Rzg2QkdEWUdBCmNpaTI2Z3dNaExBRmdpQ3ozRWtv
        bm42Qk9XNkx1d0JlMjVVQkgzUjQrU3MKLS0tIFRDMWt6Lzd3eHIwZFpjclRjNEdR
        ZlBmQWpUWU42Z2k0VE9ja0NNa2RMWVUKuLwwlsc+yyabvU+wetyStuP60jR3m6s6
        t8kghRRbhrEzpJxSU+gx/hal1L0SPbGi+PxJbnL54X9AfnJcXvMRrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T15:24:48Z"
  mac: ENC[AES256_GCM,data:VNaJ2IhisDsTrSTjfbowOqz+feVnOgqyCEp5Ig/nJWdOQosrjKk9qefAMk147DqXuE9qXxBGV/k7XEx9sPmjZHkyNFHnEyKWKp+eOjoZGBnyJNbi6afgZ1J+bJJKz/0Wz9LVC/5JilNEi5fslOe4L4YSttbhi4Mekdq+NNQKc/A=,iv:RaFjMumKB48R5OoHEmcZ7tcpHWzB/N/hqqmzvASPN6k=,tag:BJXC/3wWpwwRIGB62QYE0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
