apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:66RpItb0i7pbufp2TM/EWSALteYZtmDU0ukr3q9wTkHOeq4sGIIhQg==,iv:9oEBZYbnvjU5Rd610bYE5T6UoTfqnwwnW8XFQuuMFd8=,tag:cwUFVax8A8MIYyG61LybnA==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQ0s2bzkrWmZBc2ZLSWRy
        T1crQklzMng3bUhWNmZJZk84TjgveFZyajJZCkt2a3JPVTJtR015bHptWE9TSEg0
        NjNDRGRaa0puMlBWaDZDZmNBMm1mZVUKLS0tIGFlUDBXLzdONytUM0VZNC90L05M
        Wk9leFhrZ3hTdGlxU0wwa1Q1dnJMVEkKE6qe7bG0IEtQrW9gWK7OURubDyBVyh1c
        Ev4caOh/qyhtqBTSk/PSPGIle+Oznyk/Qph8T3t1v1mwP1twadHcDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T13:37:40Z"
  mac: ENC[AES256_GCM,data:RUTM7PJ8K94NoGGSitgY6+MFmTP11B9AKa30p61WYCQJFuV5ILEd3s8XTonqujfwkXnGulkJ4IxkYkqqKf6bzV0obzUGhgdaJp10Lc8k7jaujJZaeAaajmGTo5WWbyRDNbudV1ZH+z14whISU63bJKii6DdVtQUksFBVlFNaOOk=,iv:etZVyIAdqimyFMeo305cdwVK6MrYOrA4O7jDUlzAR6Y=,tag:yomT6Lf2KADSIjKFtkhEMQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
