apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:rYxoM957DtUG56x2UrYND7akuSfSBlJ4lBWrJ1bOPXBkHNE0F65yRg==,iv:Le4N3wJQRAuCTM7rMjlKV8KQpgnou9tFkBz8vg83eOI=,tag:lLWvrf7MR2arSUENrgNC4A==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVGxDNWM1NzI4OTZ2YXJO
        SENMUEhuSW44d1hUS1QrbGJnTWVQaVl4amxRCkFyWi8xNjJNRHl6QzVzdzJuaG5i
        bjBIbzI3QmpFQkl4Q1NpUU9rNWRQVlUKLS0tIEpBd1lzRkxvMTM0M2tXTWxlVGxk
        RG9BRENWMXlCd1dNcHBxd2x2NHViSVkKSt8fs84ASgBNm6/ZWcNPQ6TOTXIWaG8Q
        xNeo1j/VRgxpyzmnfbodj7+wmmgS4DY3+GZmJqX8GBUrzfc+YDc5wA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T20:31:04Z"
  mac: ENC[AES256_GCM,data:TPpkFV3sRObxrEss81FzvZOejgojPIlKcO7jeoE6vJHFqfzRgJsNi3xBZdC3lghKntRn0Eqhrs9+Qh4pjjj7L2yDROSzgK4piIleTF2YkBg9WVPJtPtWqvu5Y0aGaHcDYQzl7hDMWMo6QNecbMiIAhjMbDS6E6E5/VWO9em/wfA=,iv:c0i/pIvuQIXJw3KkF7jP55GJ99mqFn2ET6g69Hj7LBA=,tag:H4yQSMfV9HO3fVphtDKAuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
