apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:QfYcWL4IjRrbWfhPnCirvCUQK+54MV7ssigF507FtOp0vfrbd0ID7g==,iv:9MEq1OMlLHadxFwK2QX5WKSleMt1/yLI3RqQuVI1YvM=,tag:pS0qNCOur5wniMp/7s493A==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbkxsQXI5UDlmT3JjRk54
        bng5TVFqRTBWdDgzT0tGellabkFZNXVTM3pVCmVObjdOREtES09veWFIbXcxS0lT
        bm1ISDB5T0J3TWlOckVLYXNZVDZETzAKLS0tIFBwM293b0pxajBMc2gyNGl3Q1hN
        ZENzNHkveitZR0hXWGsyQU5SalVXTVEKpbbbUVQSihwtE7laI/Ic/TGViJrxCOOd
        gszbIGtMhrxydkCYBoXg/XMr40fxBdQT9zDcBdbSZzHQIVxdW0S3Fg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T13:28:49Z"
  mac: ENC[AES256_GCM,data:xZPjErVYxygvgS7oDV/UsKbAr6a31mKEVJU508Ov/k5xBLhDcqAzASlN7e7LfAYvmFYOriqUs022EAlsBSfVArIS2ScM7uvP908NszkFEpwqka/ZFpGxmnSnsh11KWL/2kVnl6AqvFDe+yUTi6uwD/2iNpHcD4RHLfNlp9gft2o=,iv:a8UFYWmmobU1qLKXDOAidY71e0e/Gh1h7Q2ex8JxX8I=,tag:L9ibLrBMTZVCrILrvaV4nA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
