# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.1.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neko
spec:
  chartRef:
    kind: OCIRepository
    name: neko
  interval: 1h
  values:
    controllers:
      neko:
        replicas: 1 # active nas
        # type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              # repository: ghcr.io/m1k1o/neko/intel-firefox
              repository: ghcr.io/m1k1o/neko/firefox
              tag: "3.0.8"
            env:
              NEKO_SCREEN: 1280x720@30
              NEKO_PROXY: "true"
              NEKO_TCPMUX: &mux "5101"
              NEKO_UDPMUX: *mux
              NEKO_ICELITE: "true"
              NEKO_NAT1TO1: 10.1.1.48
              #NEKO_NAT1TO1: 0.0.0.0
              NEKO_SESSION_HEARTBEAT_INTERVAL: 30
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            resources:
              requests:
                cpu: 1000m

    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.1.1.48
        ports:
          http:
            port: 80
            targetPort: 8080
          mux:
            port: &port 5101
          muxudp:
            port: *port
            protocol: UDP

    route:
      app:
        # annotations:
        #   gethomepage.dev/enabled: "true"
        #   gethomepage.dev/group: Application Service
        #   gethomepage.dev/name: Neko
        #   gethomepage.dev/icon-url: https://raw.githubusercontent.com/chaijunkin/dashboard-icons/main/png/neko.png
        #   gethomepage.dev/description: Virtual browser
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        # rules:
        #   - backendRefs:
        #       - identifier: app
        #         port: 80
        #     timeouts:
        #       request: 14400s
        #       backendRequest: 14400s

    persistence:
      config:
        type: configMap
        name: neko-firefox-configmap
        advancedMounts:
          neko:
            app:
              - path: /usr/lib/firefox/distribution/policies.json
                subPath: policies.json
                readOnly: true
      profile:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          neko:
            app:
              - path: /home/neko/.mozilla/firefox/profile.default
      # dri:
      #   type: hostPath
      #   hostPath: /dev/dri
      # shm:
      #   type: hostPath
      #   hostPath: /dev/shm
