---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./resourceclaimtemplate.yaml
configMapGenerator:
  - name: neko-firefox-configmap
    files:
      - policies.json=./resources/policies.json
generatorOptions:
  disableNameSuffixHash: true
