apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:xjQSRs0etA06,iv:kadfc6MbS2ucUGuhHdvOWhkRKSJr8lNT3DBMeOfHfBY=,tag:geO+Mp5uV+PBUhMoAtUc3g==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMHU2QVRwU0o0b05pQ0VT
        QXFLTDErMGt4SDVhWDJVNXFKTG5IMm1aMWc4ClJnL2FyazFBMHNMZ3NDNGg2dEFh
        ejY1NlN0dWtFa0Nrajg1eG1WSmt6cjAKLS0tIDJreG13cHB2RjRQek4xQmgvdTFG
        cFBwb3E0VVpEVkhka3ZrTVc1eHl0aTAKUE3QTyrp60IDEm3Ol7fJCx7qtd1O55Hc
        jd/tL+jhUi3DeirhpMnSC2tzMTwQ9vrP8P9hG2Y8TzAAOCMP8sqQgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T20:48:26Z"
  mac: ENC[AES256_GCM,data:HMP3jbPpLIQ6t4+o7CIS/eUTC9l/ymIBaxmMx/MhtdGowr3xNho2yGbcHuxoH5EPzoejOYGGp0svaGmFnPsV5Idn7KPl3j1OglNj8Mnpbm8009WXECfBoT0Ivdp61ZOMFhzpTRMsj/wDL8vuJKWTZ4JQ8tGElqUOVL9dOoOgii4=,iv:oM0l7uxZPljK4kuXKZLPD9mQQ26UMc5ADbQAWXL0mu0=,tag:LibUsOVuI00kX9KUZ5mFww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
