apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:UdzyK6Wys/Cb,iv:a6kMcwWWzr4FRP3fZ74R9nii5GPojo5qRYdz06Z3vjM=,tag:uKi/f/ca9bwXiBMkUxuJGw==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNHorM1RjSHdlZzRDaVlB
        aDRTV3RHNkQ1MjAyOGErTDNnQVNhZnNIbWhjCi93TitrWGxQSENpK2FudzF1VFNC
        Qi9zb0hkRFM1dXRoa1Q0UkNFd0dGRlEKLS0tIERCc0FMTzNCRE9MM2p3Z21TNG5h
        REN0VGJuNCsrSHc2L0xCSkhNeDI1T1EK6Ki68X2KAQZ28yLy634yZAZixI2s5BbA
        flis6R7olGFii2JRigw7qulGaV62D7JuR+rtoxcA+tWjmXMXoF3Jrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T20:31:04Z"
  mac: ENC[AES256_GCM,data:ro5W2Xf74qIoL7xPaAITU6mnOv9kCwxunDFMMWpXSeq4mHGXYrBMr0xGVLHbydW69yImcHMPHF9ewixa1VPVDeTQ2not5UAMXLz4uyq7DAVFIMxO3GpRNxY+S5EVEdZfQRL8c6G7Gp23VKiC1cU9RqRWG08Zn05rJzQbafH4cqw=,iv:Tk3Kjd3NPXI7G+oCAvs9ffFhzaUWZcLBPaRWhuub9OE=,tag:iQ0rSL27mxzEUUpk6ix1dQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
