apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Hd5SniU7JUFc,iv:mw6SBWrzr1UCelWCJXcxE2JUZHo2tyBJobmRjRQU3pg=,tag:e+JuoZhbHYH7XFkT7pIdQg==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVVVNRkRnWkVmeGczaUZ0
        MFQ5WWZtUG9xbDN4dlVQREF1OWlhOW55dlhrCndrQjV1WXBOVVRoRzNmQTV6LzlE
        bVJkcDRtQ0wvVzdTNnZ4Ni9lbUsxTmcKLS0tIHZTbWwxQlBYOC9WZEdFMWpZczQw
        bExOOW45QTI1NktOYy8xRW5WRUJ4TmMKqKTYNSB0CKvki5vpT/4JhOAJIFhwfX7x
        Ruxo9dr29LUMuT7NsjiapVL2fHvHBi0wlfEF7Gg8PeCHLyMFoXqrPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T13:28:50Z"
  mac: ENC[AES256_GCM,data:AN9idesydyiem9b2rqqrhd13/Dtq7aM/PMpqCEzOE30GFMH/esb0K4i8A3+GOBUM6Bdg0Q8b8ssT1VXnt4sKJI2EA0Az6sB75OURf17YxUfYoCUq39S1Br1LP0zCPpQYUR7EJi2Rv9WXSCirtKP/SbXHIwUuW261r5GuB6sU70w=,iv:7Qf/P4WCpXY0a6r17R6LYnfFUdzULiiwTWNK7M402y4=,tag:vk85ceWneKj5YyASHsTGhA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
