apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ERTGuUWUt+iZ,iv:lpzT2X/dbpQpmevnV34jXP4lO0xIAuHXCB1JNpRoIJA=,tag:o2ap1aYHS1U7RjjAv2Apvw==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUm1VODFPdmU4bXN3V1Jq
        akowQ2RyZk1YODlOd1UzZ3hUZHpNU2c1akhvCm02OXU1UFhxR2M3TU1MdlRVWllS
        bm4wZnB4bW93bHdkdGxtbHlsS2hSRTgKLS0tIEdOQ2RtNVlpb2pEb0djU2pGNWg4
        VWpKRkN2R01MUGFMYjlmbG9vdC9GQ28KlWBTcBp6Rwethf3ORa9rtqxR4i3RHNob
        5gn5Tvw0w7BP0l14PvSSm3jT6YF1x672zGIEeRRuPAkPijMarpthog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:54:38Z"
  mac: ENC[AES256_GCM,data:Dwrst9kPy946ItW8H48DFuDuqqYwdtOQcbWP8L9sgzDwvDvsB2D9TsJjgqvHRJ3k7kZkzAGCi3HJu/5F8wRfRjmj05P0ONEP/cUtJxOPLPSUghPEIjjcPtQLGIvfrKUijgRc0ZFvWjA6VE4WDY89ngF8yXWCf6KVZC3nqcKpnD0=,iv:wwQLEEzsCx0h9KRqiZR8zPB+mS4XYZdAkq0bvGkvYBs=,tag:cAkh76Zv4ZqwLIgKY1j+KA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
