apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:J6W0DoWzQlDl,iv:E0z/OsNoeG+x/lit5NzkokJzJX6g/m7pEd2Xd64tlz8=,tag:uY0AWhdu1z5VPBJDW+3ofg==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUR1ZkpKTHdVbVNBVGJs
        ZmJyL3IremZXN1E0S2drem9XYzdvV21Kd0hnClR5Nm1FcE1WWCsvMjh1U0ltSzQ1
        OHVCK2FJVkI3ZjR0RmxUK0tVd1kvODgKLS0tIGhsRE80YXhxbERDSEd0TFRpbFZs
        UXFId2tzSnRaMHBXd1B6MVUvQmNuY1EK40CfxfIvda/PSYEMV0x4mkjps3wKyZS5
        TSYmMrTPY6w7snLB7G8qcc5Gi1mF76QWTPrg6JhBVxj2ntTyEMKnlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T15:24:48Z"
  mac: ENC[AES256_GCM,data:VcyycBCn8inapJT7/JMI3nlyLYWn5xvZrzA9u2ARZM36aieplRAW+wT0x4XF0aq0MP6u2Kmmpq34cQqEQ2VXDzXhW1tLRpTOrUClTTv493yHe9Muxz9hwWw09M3wDMwLWd5D+8i47UoKUNSjtCT9hVD5YhTne3zFZTU5TwSWnns=,iv:XAqfuXzlDE74csViPPV2644ceRYyGc4ApDq7HTJghVU=,tag:FVASj9+wN8jp1GKzBzGaSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
