apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:DWkUiY7vGfIV,iv:MfIcxrD7YDuKmdx/c3i9P3cF7oXfxBBmhNDp4s0rUhw=,tag:orsIZhBsblIIenCDdJE8zA==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0anhCVWJLS0ZXanZUcDE4
        Zm9RMWVVb1RmRUdxcGdkdDM4NU1nQ2x6Y3pvCnU1NGJxVjViWVhtNE9OdEpVa0t5
        V1dOZUM4RDQ0ZlR4NG11eGYrOHVkVVkKLS0tIHFVcE1NSVZTbkRVQXFRU1hLdC9t
        OXdsNnZFTFF3Q0NsU1NzUWNWZjBwU2cKEISFs6adygebB433kmzgt90ap2rmM5n7
        jxKB/m9okR2TQDrtuuA0TkQ+9Y7B89cgYDSw7P4e5wUvnyjIgRA2hA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T14:28:49Z"
  mac: ENC[AES256_GCM,data:u4mTtqKYoj9G9d4aKnNaPooQp6LpdiFe4f5XkBK/71dy9VoOqFRSadmIxJ662mlNkt3kPDcA5lVgwjyaSirmeYtGTYvHIo0I1UOvLPyz0E1RSkCQDiaYi4OcDNIfEvtkUV9FvGoVcQS8cscDZYKUP4+wE57ECWbErrUcoDmJ0no=,iv:ClSol5xHamGnCiO55CV2xo8BtR6PgPwSn30mWL9vPUI=,tag:DGdVnZRFmfoSuEZw1Psu7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
