apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:HI0tMswtSLYj,iv:QnfBxNfsQ+jaAYlExWcF2ziXlGjz9oxH/bM6bwer940=,tag:xtMJcU/97uyV6OWUlksRRQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMjJWS2Nsa29YMlRESzVZ
        Zk5DTTd2VjM1cEdrWklKalRKUnlRK0xLVTBjCnJPa1hyc3M2MVhZTDNvSVRGb2VC
        OVFsY25tNU51T1V2MlN5Ly9ZVGVYMW8KLS0tIFNIeFlreG9NbmNaK3NPRUc5b1p6
        VCtuMkxuei9SYlZhRGpLN0VOWnNodVEKq4ZvUu8btyqLx1r+KNU2/Ah917r/UDT7
        wujIqLl0lOMf5nV2/ABQLH6vGHbSqnMAt2Bk13SOPZ+LHXZWg4vocQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:17:05Z"
  mac: ENC[AES256_GCM,data:Luepoqw/SPlSIO71OHwDI02HZCj93DlOQDy23yC2RhXHQrQxW9q5BaQgdOI8pl8faRaJpNY3WZIl6j/HKQ9R+r3Cr1rHjxtObHxGO6ltmdms3+ebwyhl20tTP1pV6x/FhnMjoE7gx+s56cwrFx1bNFmW2poIRO7/DfKAiStEjFw=,iv:WFlJB7BSCcWxlH+DFX0yFwwWOb/gfqqLuX6MOqU/e8Q=,tag:yQFC6orFYS1VDiOEdFq44g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
