apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:6CCAUilfgCAv,iv:MlYsgvcfBrfx9VBpatai+V9wvgLBYjDbgkkgenjeFas=,tag:Nf5NEWBxtFRRQDSEU82czQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUzkyQ3lkT3EvR1JYaExC
        TFM3bHhTcDlCS1BBU09pZVUxRmQwYW02MmcwCk1EVk1hQnN2OCtUNkI1cjhOZ3dp
        V1J0V0RkWGF3SkUrYjJSQmEzWllnYmcKLS0tIHZtWHRlcVJjZk5JQUlNZWJlQkh6
        Z2xEMlpSbWNWTkNYRENUR0QxcnBwK1EKOcp6ddEFp3tTPIvgB6Z5sIin4m0PLjl4
        W0Ab/tdONL1f2mhm3z9Hmqa26kqrTJF3K+9FLAW51uuVjMvNIl7knA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T13:37:41Z"
  mac: ENC[AES256_GCM,data:y0Q6sPlmJLmuM0ODpCEbWUDDkZNz6QpyFwtEtcDHDygprG/HIrlXMpx0fqX8ZtTvtLimsUaaIzdpVj7BI3xqyLDDno63Et2snDnMZjuWBb8UI4zrHNONnX20vdXWNOS9wRuB/twbQQ09V/CXV/IEUN/MeXxvgN+2l5rL54ZkiSc=,iv:jHkB4qKOVIDBzqWoLtPnWeJZOlKIVFd5M7S42hCrqg0=,tag:OOt/zYw+q6g78VLuZw+5wA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
