apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:2i5xsMw2tfACl+a2ntZ0RLdxA0XszxuMl4a20vg4MHU=,iv:kZHhZqkdPEf7awVeP/qmk6MdmSMgPNPjpOSG1i5FIHo=,tag:3920sghV2lzqCNGLAo5GxQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUDBCSDRZVFlPWE5tT0RV
        SnlkSEJMSS9ZU3lMbjdneGdJT05tMWRyR1FVCi8xVEVHcStwQS9DQnNMZCtXN0FT
        eVdiRW90Q2srWVp6Zm5UL0tqdVlXQ2sKLS0tIHZHMHlFVzdoRzFjT1Z4dU44UDRn
        T3FuWmx0SVRBenYyMlE1VTBUbndYaGcKQjHHwLaVXcC7N66Sb/1mIglWCW3clmVY
        4aVLoJ+eQfJtbzw8kOCOoK/cy7B/d/yJBU6+XnyItmbiyKuKfl5N5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T15:24:48Z"
  mac: ENC[AES256_GCM,data:Z2ukhvZifJxHNKSExMigU7qfYNeuLjS0x2MjbHEJH1PqQlkAtR9WE+vej3z8WmQjlvOUurabOj/eFRfV5AOKp9Z+UxV/0Zo4gE/ElCaj6IlN3CX101qXGilUpQFsK6D689hKo6Psb5rG5N9MqgmHG1dgHiRmOkKz5PgOmWSn6Fc=,iv:2x/CeBhzzif3r4o3Mj1FyJtvn8ShU6bRKpL1+U/1SI4=,tag:7NP0MN8xe0Cu+8pfZzKajA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
