apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:rzQ5KsDVqnYeMwiCKHoXIKZ6/QVEJYddHRLx99Q3Dns=,iv:mvwhVTO+OSw8ty4ryHakYsGxlcRtB99zWM3paW9CGwo=,tag:H4afJWOOFlYVhgUPO3NIgQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMWl6SU82THVuNSt2WTlP
        bzliMWw4R2F6RHcwQWdMSFNWWjNoRHN5dVZNCkVyMldaZDZsbkN2bEJabDJOenRj
        YjdXUFdsdm9mTVl4S3VyNFRleFM3Q3cKLS0tIEJIaWdibEdrVEdFUmZEclMxNEJz
        cnowdUJOcUljWlRoQWh1NmY5NXJCbzQKXq5/btJgN1t8qWv18wbJYDIZskZRiuCA
        etp8Nj82eVe+zNlF89CIOS5GO7Zr85kbyrQCpw3VxhV6ZI2uH3Ouug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:54:38Z"
  mac: ENC[AES256_GCM,data:Mn7eEkz6I1N8okENNgD7CY2eXSpQE0cClKhHrzdS6bmV3K9FaFyQ3mMPb82l6CLDDU2cIa7e7L3+cjWJWVjErBBmSBfCmJFh2ILVib4sL8Mlo80kqQxi4ap4CUnHRL9qNegQnW+maawV6XZmkOAHb/9On8DrFUrtTnUNoxZTT2Q=,iv:j8aHo8bF6upqlwXlCMWZZuyzhp3b59chkR9AtzmB6us=,tag:aBCKjmrMfdgyWynusCcICA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
