apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:6zrJ6cP/YPS0pCQlST+nAWXYKjRLsy4ELKq+e7xNTlA=,iv:96iTu8fODtQ7PqmgEhrB31+w48ZvpdFR6pviltabOGk=,tag:mCCXLg1G4KbngDW80EOgZA==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQXFuWmUwcEdzYmY5S2cx
        NlN4ZWFnZjJZVm9nOGFEZjdNS1cwSHZHeVRzCjJtQ1JvTFlvWk1pZm4yTk85Ni90
        OEU0clFQckhrTFNpNysxeEhqL1B4ZTAKLS0tIG43UVErTExEdWp4c0t2aDl4VzUx
        OUtFeUJTQ01WSmpjUml4ckVjQXJ6WTAKq9r2NeDTGiDWqFOxWEtR6kqt3o5V1eH4
        ERis4BAGP93Uv3FXVGTgPFS28v8/9FRBXkMNNk4q+jEwC7Sw5xpJgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T20:31:04Z"
  mac: ENC[AES256_GCM,data:u2u6IHII8uglQYNxk93KPPVENZPsmqriHIDL5rmWCP+SGqpdgOI7bSN5UFNKf+MPrsK35h00yYQdFe7W6zRroHL8lHg9tkJagZr+lgINsPbFueWcdiYdNvHUwVtmTVSseRkABfm3zCVZPSYm2c55CWA7RvjNlXGUDLfb75VW248=,iv:2/L5ozYosBTutcKqd1qQ8h7fvPHgtUofdHWHEKlY3+s=,tag:9aw952VUY01z61Eb2SPv+Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
