apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:U8b+TeUQP+zL8xA796CSQd0NGHHfCDDiNmV4p1HPRus=,iv:R7A38Kb7KLqVFhjVJ/DftsQUwFOHJUndnJXMo5lm+wY=,tag:ziykzpbD57NzqpF7pmf0Ng==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NGpqam5oRmVRYzZhcFNY
        d241YkpKOEYyQ3kvSjdRTUxHaUVFdXlWamhrCnNWMkNjeGJpdGcwRjIvMXNiakEr
        WDlXMWU3N2tCYklLZW5LYmlNNm5rTjAKLS0tIFNiOXpVcHJkY3AxUlp3a3BzdlNr
        MFZjMTRILzhBVjNmQmJLS0FJY0RxT00KNJKWmeKpq1QzdE/3iQ7dl6I+DWWwZb+v
        qFzekV6e37l3XYM06BY7cNDOtExhR7psqz9PTJkndMNDxdM3D9pYhg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T20:48:26Z"
  mac: ENC[AES256_GCM,data:fq+cbg5YYzIJTd5Jw+8TPd7P4OjB7VWOWo8widzGrbba0QsmrfkR+ATTeyEuRRmK6ysvS9lZ2gpiY7OvH5cXK9lDjUOKRnJewziajRUaGRJyF1LRBAn4TWL1XlNb35VfqpR5RJ3FvYpdMQqkAm7MTmK46gTHEKIv2a/Iz0u632o=,iv:rxLHofb7pezRIVIfjbKvBBOyB2Ic75uMDWL70/Aic6I=,tag:NHH3TT6BpxnAGqbyL2rA9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
