apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:waTK7ziHcDB7sCN3k7OY9ZT0Ra2cPUZ+WXENRrHNyPw=,iv:lipeeQJr47GhuVRid1D5AFpDjU0b8OCT3NzpW9ts57Q=,tag:lXCDgLcBzUElrCWClVE1OQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWTBFaWJ3KzYyaUF3M3VM
        Y09SdS9HV3A4ajFPWlRPclFvVCs4Yk92S1dFCk9JeTFyTWNRV1BxcU1GMXdhL0ht
        TldhUEdPR3B5dFRLQzBMY1gxSmQ4RmsKLS0tIElTeCtKYXYyYjJqSW1pMjZXKzMx
        Sm1YZWhLS09BT1VnbDBWMFF6LytWalkK1vEv96bTDzcgBGHVViIG1fVCue2rPwsA
        2s1c8s/l7LAzOUji5GekST0PpMUmRVDpMVU3AcLE7r1OVG1v67sXfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T14:28:49Z"
  mac: ENC[AES256_GCM,data:PpzTacTxn8lKf0kGD+C6JKrULwwouBJqst5OggXQmH4mVVW1XDmKZ9fW/EI34dIwOBkbpa8lGrAnFN9ITSW3aHCMTQLJ9THA/FO4/hgpzaf6i7iCSpfqm2yfpTUYmDQm+CzkBsA5cvJ/ORukSv/b4+BNFYyKIwHA8sjfRHzyyoc=,iv:BIbBB8wPkYm+x/BrWwYWsfHZVCLkPNCxWnDYz+rWl0Q=,tag:DqcP2+e05+OIcQgPj26QKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
