apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:JoK9Q6ZZc/vUOBoDR9U8+tEPozFfMNrqM2zalH3H7o0=,iv:CyQCHsBuEsVpQZFF1uL/1iUdGvbvSLn+YiD5pYyCYdI=,tag:6LGZgQi4gx32J1fHsG9+bw==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU2xlK2p0TFI2YVcvZlZY
        Y2xNbEJnL0Jxb3NoSWJMelRQMWo1allORzIwCjc5NU1iZnJidFVGdFc2QlpDdkcr
        Ri9ucUtZMHl1eVQrY1RtNlhSZDRvc2MKLS0tIFBJNUhZZEY3Slh0WTRjOXZzUCty
        bUJpeHVTdWQ1R0xsSnluWTdmZDhnSFUKi2Cufz7unli1RAl5xRh+uVrz/jm/QwZ1
        gmlxfrDFIJ5sndHKV17SNaeS1Dxw26LO0rD5h9T9Stk7SOSlbYhAIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:17:05Z"
  mac: ENC[AES256_GCM,data:ShJDRNDkCbxR45QNBDO20rLzEO4Nj6JI6mwkaEkN3AqjZsRceMvMAtjmq4e8pqYoABAKWTu26S2eMLMkZg7zezLOj4j5W9gsdSZjRZPPYAyuWlNGaMDrTs/YHiWx9mlVGfjIiEUyAO883MG4WSPi2t3bPj+lZIp2q1+ENcpiJRk=,iv:uoNpnpVinCMexFBQac+XwGZAqz00D1BuUEd1T9013MU=,tag:X3ysnPkGFzDp0n6R1O6LYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
