apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:QhL5ogeiD9Jxps8VsQPUgOmHbM6cLS8TKWE/ALoRSdc=,iv:xe0p+7a8dqA9iDHugXD5ToufS2fYWbVC0LNWwte2bRk=,tag:iD0qNJJOQLlYEMygEi1PnQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbDByZlJjWTN1Z1J3OGFI
        Ynk4Z3U3cm1OVTREb0tiTEVyKzU5bGFpTGxZClc3bGtsSWk3Z2NFamtnZWVKL0Yy
        aGZKQnBicFUvT3Y5TmhsN0grbktvSmcKLS0tIDYwTGZ2ME9odHBKODhXMFc1bk1T
        TVJ6ZXcxa3oybzhzcnFHN1R1VWZKaTgKTTjEmb4x8PNcP4S1smtdYUuAnXXeGqz4
        jLdpfS6yRipjIIq6bkZoT00hjLi59EaKdfCDjaZOIUkD6PeVDIvFsg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T13:37:40Z"
  mac: ENC[AES256_GCM,data:ShjSCpjRmVuFJShDMb9k7Or79PwlIpFoGXon6k/V1k2BVkQ/yUtEIBjYbVeDLhfGVV71wCh8N3o8OMSnWMxKWP/MGRA4Va/GiycD2FKIoX0JxWL9AmN2Ixvlzrghln2+U9zAKf9RLDebUTLMhXmvOQUFNbQ1TDKzXkrjhSansrs=,iv:fMIIq056HDhIEkYJ5KXwX0269Leer0MeFD8TjSUmQPc=,tag:zI85ExB5KMvJPs3zaCzMQA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
