apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Be/lfe+LB8Q+C41YzekoeYtkcoMCHdbFT2Z2NWIjmic=,iv:+gjIB8owExtCKJgjsFJlEyjdvkAonikZwdiojmB1fI0=,tag:ZHTCJnKu692HD84BBQmA8w==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUGFPNlRKc0xoZXphdUJi
        SVZnM2lCanArOXlFVDdPM1FuVUhwNTVBWTFRCmFvWGd4ZXR2N0E1MzNMMXN4cXA5
        V1gxQ1RDcGI4UGxiV3ZNcnRhRkVublkKLS0tIEdDNjRsY05McnhxcTBtcUV0OVZv
        ak1GMC9KY0ErWDZlT0crdFppMTlSbWsK1kkXGEQ4s2m5ZLzGG0daYiY12WMLezHN
        ABt2hR+tWgqTgDjHfYQv4faM1fBqextEfGRc42/bMNh7eMwWIHFc8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T13:28:49Z"
  mac: ENC[AES256_GCM,data:KffSRmxhWoamRlLg/fhSUcmCNkKbolgZ/8vTfbw0IRTYM/PWIrJlN1qudnk0BJcrN2YDKRnHxr9pEHr2MOD7qDuMGnHO4nWQstWncF7dGhmG6E4z8vUiMrCBAUXe5zqXUJKd1/wQYGmGmJXFO/jKNxAgwf6QTU1IKUKXhrr/nNg=,iv:gGQTgIHp/la1ceQdq3Au7KEm8vnR1EreqAJKjDLTC+w=,tag:xP6kHwEciJyNsYk4EMsVow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
