---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: renovate
  components: []
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: renovate
      namespace: gitea
  interval: 1h
  path: ./kubernetes/apps/gitea/renovate/app
  postBuild:
    substitute:
      APP: renovate
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: gitea
  timeout: 5m
