---
use_default_settings: true

engine:
  - name: bing
    disabled: false

server:
  limiter: true
  image_proxy: true
  method: "GET"
  public_instance: true

valkey:
  # url: "redis://dragonfly.database.svc.cluster.local:6379/10"
  url: valkey://dragonfly.database.svc.cluster.local:6379/10

search:
  autocomplete: duckduckgo
  favicon_resolver: duckduckgo
  languages:
    - en
    - en-US
    - all
  formats:
    - html
    - json

general:
  #instance_name: ${SECRET_DOMAIN} Search
  enable_metrics: false

ui:
  default_theme: simple
  infinite_scroll: true
  query_in_title: true
  results_on_new_tab: true
  static_use_hash: true
  theme_args:
    simple_style: auto

# categories_as_tabs:
#   general:
#   images:
#   videos:
#   map:

plugins:
  searx.plugins.calculator.SXNGPlugin:
    active: true

  searx.plugins.hash_plugin.SXNGPlugin:
    active: true

  searx.plugins.self_info.SXNGPlugin:
    active: true

  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true

  searx.plugins.unit_converter.SXNGPlugin:
    active: true

  searx.plugins.ahmia_filter.SXNGPlugin:
    active: true

  searx.plugins.hostnames.SXNGPlugin:
    active: true

  searx.plugins.oa_doi_rewrite.SXNGPlugin:
    active: true

  searx.plugins.tor_check.SXNGPlugin:
    active: false

hostnames:
  high_priority:
    - (.*)\/blog\/(.*)
    - (.*\.)?wikipedia.org$
    - (.*\.)?github.com$
    - (.*\.)?reddit.com$
    - (.*\.)?linuxserver.io$
    - (.*\.)?docker.com$
    - (.*\.)?archlinux.org$
    - (.*\.)?stackoverflow.com$
    - (.*\.)?askubuntu.com$
    - (.*\.)?superuser.com$
    - (.*\.)?wiki.*\..*$
  replace:
    (www\.)?reddit\.com$: redlib.kvshs.xyz
  remove:
    - (.*\.)?access.redhat.com$
