---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kaniop
  namespace: &namespace security
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components: []
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  interval: 1h
  path: ./kubernetes/apps/security/kanidm/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kanidm
  namespace: &namespace security
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  dependsOn:
    # - name: kaniop
    #   namespace: kanidm
    - name: volsync
      namespace: storage
#  healthChecks:
#    - apiVersion: helm.toolkit.fluxcd.io/v2
#      kind: HelmRelease
#      name: *app
#      namespace: *namespace
  interval: 1h
  path: ./kubernetes/apps/security/kanidm/instance
  postBuild:
    substitute:
      APP: *app
      SUBDOMAIN: idm
      VOLSYNC_PUID: "999"
      VOLSYNC_PGID: "999"
      VOLSYNC_CAPACITY: 5Gi
    # substituteFrom:
    #   - name: cluster-secrets
    #     kind: Secret
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
# ---
# # yaml-language-server: $schema=https://my-kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: kanidm-tools
# spec:
#   interval: 1h
#   path: ./kubernetes/apps/security/kanidm/tools
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   targetNamespace: security
#   wait: false
