---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./audiobookshelf/ks.yaml
  - ./bazarr/ks.yaml
  - ./calibre/ks.yaml
  - ./calibre-web/ks.yaml
  - ./ersatztv/ks.yaml
  - ./firefly/ks.yaml
  - ./fusion/ks.yaml
  - ./it-tools/ks.yaml
  - ./kavita/ks.yaml
  - ./minecraft/ks.yaml
  - ./pinchflat/ks.yaml
  - ./navidrome/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./redlib/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./searxng/ks.yaml
  - ./seerr/ks.yaml
  - ./sonarr/ks.yaml
  #- ./tautulli/ks.yaml
  - ./dispatcharr/ks.yaml

  # - ./threadfin/ks.yaml
  #- ./xteve/ks.yaml
  #- ./romm/ks.yaml
  #- ./immich/ks.yaml
  #- ./komga/ks.yaml # use komga when needed.
  # - ./lidarr/ks.yaml
  #- ./ghostfolio/ks.yaml
  #- ./homepage/ks.yaml
  # - ./readarr/ks.yaml
  #- ./stirling-pdf/ks.yaml
