apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:LGZJJ3MovmL6FVRtJvtM/X+RwdXgQJpmT8310nucwylAx/S6tIC7fbcBm6jvhNh5fESnGRr9Nx5X3Hl2nnEz3Z14Mah2iyknMImRemOosA8L9lDAIr2HxVW5gwYdXMCYPBu/cnGX8d/EsTVQLETFvm9Fj+99BJLSiYGZUAAKLcIp2F/hvVP/4pzcX/dzmyYwBGJEHPeHNAjk2OGl+0G/MArc/b5bpuzNRvrJO+GUN869CA+W,iv:vN2tYc2l5cP9rzFPdk8YSY5+Iya0OlcfbYK2MUQddpU=,tag:etdMvjxL5wvudTnmh+aaiQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcWY5MjdrVlN1cDlGUlVz
        N2hSK2NUVGptVWZtT0VBMjF5dTdYbW1wUm5FCmNwNDR3MCtWUGVnblB3WlY2Y2xy
        bzM3bUU3N1grMnRVMk5zWGNXVkN2bzAKLS0tIHl2azlGTGlBb1oybDNpOXZMMGRr
        Q1o5cmhnam5MRm9CRExZMUNadVUyZ1UKkY6p56uqpcnMmTl+++J3DsGLxu0P+NR7
        59SryCTlNH9Xz8ZVM9vf1qF8pCrOVNqX7xTEVM1E0JB4CBBfzb6Vrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T20:48:26Z"
  mac: ENC[AES256_GCM,data:1KtEcYvDiwTajlFGq0hthsq82/LSDyIXDwwWh3CcLyoOhDlfE6caDX9mS6Ieh+JHggFpcAYWGgAtWCJuaR77K+g/cgfcn5bODwaUDuMJ23ltxImJycblo4Jd+RwVlYoH4hQJriw/ZLLdbP7DjNbNdut5vli/qaRtsQ6skyjSO9M=,iv:lyXoD8nTuc6mHbwNhUoKtaqEKRmY33/ZjU462WV4x7M=,tag:T5QO6+utJ7+WeUBP420dNA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
