apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:UndMGhlf3n5fPHU2L8L+tln7WRExgxjkmAb+k+EdxUyC4uT01T9PT2PWfgemBrERmGEdhfKIRFGEm8n7qFGq3cQybBHft9nl6Qz7ewOcEqzs+mZKgwc4HvVbsw7s6ks+nU4vNzlYR0viQzchTbTj6sX7r8UeifBiHjGGxD7qWS/GgC2vmlbgMHQkKGSn42k+y7/Ej8+9HH18PNI/ytS8W61EY4apjojULHHFF2IwH6cTJ7zy,iv:EMn+N+rjAE4pQhiwpo0AVCrsTeO86/VIwu4NSlnlmwM=,tag:Er7Sh018F1cZO2c0EBS6Tg==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSGlSanVGNjBERkJHVUwz
        RzRUYXdlZ0lpNVdRTjVyWFZneU9SWlA1eVQwClM4QjVUcFJtdFdqQ2c4V3AyY1pU
        cmdLcTlhYU41L09vMGFZNk4wczhaOEEKLS0tIE9qVkRDemR3eDVJSEg4cXpEQTVW
        OU92ZEpxUnU5b01JTjRmMllqZ3BVQzAK3o358B7RefqDoNDYXm2cuKe+4GRcqxJB
        gL70QdO9KEjdLPxa2dq0HTJQs3RAb9j3E0B145pXea+PyyqsfPtOPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:17:05Z"
  mac: ENC[AES256_GCM,data:6hXd/kBXq1fsFLqVsOZ52dbdDIjINRy/yIxI1eeIyID4LFydQbUDduO9kDpLcWLYuc/wLxVTIPZrPliADWOSAcyEZ5yN6kYOM3kkHoX/00oe14U3EOrILd5WeGKa+wiiNL+MGvyZ2Fd6EQ1+KOb6qnRPMb2fleHvCM5FjgZkriY=,iv:vJDXjNo+gUU7qSlJqEvs2Ixr9dJMAuDoyN86Tunb3OA=,tag:vvKmHmeS/VMjE74zAk1VpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
