apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:RcFrtCTIlqEfKHBA+lDzVdO1q+Dmg38wIuZPVF5OmHlubT9pOHp0dbl+ucYJURwjkJFBMfVLHnf9/D08QOu64sV2UvpDn2zxPsJCMiPgobVGpu5Ep9o+KsT3CNcy96rDuFHBB6xanxiHoAaYU7wwBj4/AZtWbPhL4BHjdWwSxTX6DzrrPRqAv7nGXBWvQvHO1GAT6D2N/fBXf5Q84J5Rbbr406Cb8VVp3z+6h33rjqjjoNZS,iv:AKwHPNbs/tKzKfXtXekua31dvj9au24zx7VhytepL3E=,tag:+61MenztnZKlxJ3jvtqgCw==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNEJiT3AvQkdoTU15TzB2
        TS9aYnVKNEF4OWY3ditRSW5KdjlJdlZIU2xrCmx1cnpoMEJNMVFJekJkK1JZb0ZF
        aXh3aEMxWHFGZEg3YVFJQTEvRkgwUTgKLS0tIGFVWSs1OTE4eFNLd0JlSVVCdHQv
        emh4bUl3V0V2R0twSWlkbUZPMnNFS2MKKP/S1LL6f72d+ltblYgrD4N3w/HqFTLv
        C0aH1r8umnz6/vJ0V93u3RVSElP4X5rFU4VRRGsjJ6WwbFye4f87Eg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:54:38Z"
  mac: ENC[AES256_GCM,data:cyvH9M7xfmMWc574coevXXwAlw6p7KWBUp65orWfx1n5DGwGJSL4o4xFlr3h+OLxhUg5fO0fJPJJj50W74ssQtm3+A/EGrcyOj+h5zvposUA0EIS29Mqyger4KlTRQnUgjqSjGfkz1rmhjMvrmlKdu5+k2QuTMU9JA04wBRuakU=,iv:pvy+Zd4GNbgLfYw1fXOe7TIfwoRvMNT6LotfzhWbrAE=,tag:R7i/rl1xoyV/Jmgx2yqoDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
