apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:yh4Gehir7qmgsU2tWoxzQqrXLt9KQrX463wn0EQakEZ6oTQMop2Z5xleXP876rG5gTmKi1yMkMZApTUDPnHjFezxJ0Q5QoMk7osesNGd0ck1aU/KSSuNzlADgC/WdzW+ZPfbh9bAPznZLDYSXV8+qkWdjRX/cNRC1GJRR3to5CnXhGVqXL4vQ3EteiF2Ga6dhbs7VSyREniGyLCBAmYG+z5wAYMvXhUfoHMJcRWDgYCdGypC,iv:be/TjiDzrZFHYEK757RdbVSCjhOxpNo7Ff5QyUvYdt8=,tag:kcBTv3BScEicdkFURIqCmw==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Y0ZFK2pxNlRaMHdNOUJj
        blBKMWhvWFcyWGpnZkxLMm1FQkdMMEtCRHhzCndVajd3bjM0TnhwdlVwMXljUzZq
        TlNZSGJLS1Awam1KWWpqTTVrTkYrMjgKLS0tIEtoQ0ltWkM0SEx6b3c4U1FnckpF
        YU9qTHJJUTBUaHExakZJUUplZThrS2cKpTxSAF+Z4rpe8vZPer+7qpSR7G8rOYmD
        MNWxbMoxlNMilVoGT+1Zcj2lrfz8Nn3MRY/wBL2molBf5cushalpqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T14:28:49Z"
  mac: ENC[AES256_GCM,data:6pp3XwX5SHQjw1gZZkNCVw8s1bEA1jF98G/PJ/npYOm11pNWiI3bmtismW6mzEAjFKhlMYOeIyWeAfTwql/38A4Ue8ne68IZKsNSMLO+tRWPV2plmRp5vWXRVpVrNr24T1yA3+l5GWEWsCJwnd9/AkJJWXscO4A7bifFNMqAGnU=,iv:dEgBHtVdUpNqBBd1GzG+XCMTe4ZiXYLN7sriYTMxUWY=,tag:BPfzxZeYkZnJSJD91dtCSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
