apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:bZzDgyi9Q5NwuAxANXD4mRT6Km/olvWph8bTr2oAFoYaBNPiaF8M6MU7OeGcDsqsoIWPf7DDIKU8Vm5/DK3QNfzbsgA69v1vSH44/WUUlG+EIQh/PUQ80s36LTGmBbG54uYOOBt10Kb8YGQBzxFBVkKHkUmLcTqpNTx3RSrDA0Enh66NuEgi8y+MlhE4eCB2nk2F6Mfw1H3/eu7bwrrxIbp7urqaH0AKUrja+RtSMACwCGtL,iv:J/SQfxBcLi1Gl2yFL61TSGXSh8NP10paE07njQu9oLA=,tag:G9JGb6d55/PVhw7AGqhCIw==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVWxzT0tsL2lMZnVBeHQz
        cURlZXhURUx0b0xEcEtaMkJMSU9nc2tJY0RvCjZuV0doNWlraDdySlJPQXBPZW5p
        Qk9zRlgwT2ptZXlPZElJTGhSZXlMZzQKLS0tIENHdlNVV1lFNGx3UHhCbjgxL3g5
        dkYvOHc4T0QrUEpuUWI0dW5qTk1CR00KpeYmac+Wl/m/DZUZRoOxaiJokYp9paCS
        mVX3jl7RWQuRSXY+lAyVU9UZnfOBmlLT9JzP27+zYFNupH1pYwdxwg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T20:31:04Z"
  mac: ENC[AES256_GCM,data:0Vh/YVGBAPnw0i06TOfKFDIPbezdgkNEJbtKe7W8B20L7k2Hxrjun6n6x3k4i+OnY3i3W7MQcJqCCwPjflVa6aJfWUh69wFcyQHtcH+4ndpceBACV8xRQdwn+M2blZO6fR8gsDxYxYNPLJl6L+wPMDzN3LkCQN2EHY+/87gh/cc=,iv:6odxF621inPHmV47X+gXB49fDtzKzOZpbkie2NyBzgk=,tag:7yV2PPcwyTSU43NxDSYLuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
