apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:A7X7kZt3DX9hPeO5+WrFhVtWl1a6uX9knVp3dbFq4tkMYLTWEGOwh5kx8CKMsXHDH7BxisCE6Na60AgpIC5doGONUJECcaPajXNX3N20Dw7bNDqJmCSQtjEeaw1QKcTHDNslZ3JRv+ihcF5/28bgFnC0bJLTJ+FNAYJuB7yqALl55+oKr7LkE7Vbc4aKkMnS49U4JnSXLAQk4TOWlUG8ppNa39q69djx/JRjDv5Rx8mZxsyp,iv:mPaHgg5RThBUpbfxhu25CtYzB8LAeixi2dyPPxz7bDI=,tag:rndomFhv0dSb9U0rbQii5Q==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWXB2QXFZbWw3UktiYTFt
        OWp5Wi9Xemt6dmdTZFpCNUhsMWNHVG9IdkVNCjNJcW9GT0dnV1lIVkxmMURUcFI4
        Y2J1TE8yaXprOTRCQm8xVWpMUGdIT0kKLS0tIEZZY3E3endrRVFKellnRkV5cTVh
        K2ZOMjBXUDAxenIvMUI0SGx4M0ZZR2MKwFqUipWOERxC+J/zsIVj6ZtWWFNUM6nc
        TrOsweIy6HdNw6WqoGjEdKiCAQ7CyFAgA6QssshqfsPO6X0sWHkHcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T13:37:40Z"
  mac: ENC[AES256_GCM,data:f7SuCtZIRLuZgzwOnbzG/tvYTjxSk3Li/9dmQ0ZCyM2bOvLE0R18gMHMMUvItrh/8HAw4xzySvZgqWMJtApvZkepevClu8PEXPUxFFZ8hex2+E7G1zlJtCGXDaMzPteS7aO4daS68PvTDU+WXzyLGV/BaHRGjI9LLVeKqx/8+rI=,iv:axo+BoDtpT4f1XQ/k5ousCAzD8r8T9LWTSv3CVt4cHw=,tag:Hym2kwW7wqts7ihMAaN95Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
