apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:eCXOHMngzlgopEL9/SbfHm+EL1B93j7GQQbRXxQ/JXhYV5LQ7OvqUCJUm9Sq9WzEGoh06qXuk3700dvcadjD482O3edTYUrGeWQmCi3qk926bDNI4ce5l6PpKmGPMNdLa5xOBqiIvAPXS43+XB/kYSkjPTb5lESVLUQof7AtL54fDbMbSTxXLnKPUX6vl1aYOBgqIMe+F7Z/34oxTtsbM7541fKCmuh9UXZ6N1YwWPwIAJ3q,iv:TA+QYM2DAMkH0CNRs8VfkGUghzX+PckTQewiELbNR4I=,tag:inoWYr++cLO1/ForKShzmg==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZkdaVUhmQzM3NjFWaGJo
        a3JPVEFoM3pmZHRuSi91NkNORlQyQjR0bnhvCm00WG0wSFFiVGlic2xjbHhNdUZh
        VmlaNGlpakZTWEo1OHBBZWF6dDdwQzQKLS0tIDl3aGN0S3J2Vm5iVUQ0blJTZm92
        cTZVaHR4NWVLNVJsaVFocnVzNGtNVjQK7LPc/nhKLojJSe62bpX2bjN6Nu93160m
        hqs/PHIlaHpPc2IQG2l3KU5vaADVftP8JsfexGNqZGp+6YqldD+OSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T15:24:48Z"
  mac: ENC[AES256_GCM,data:43F4jl+vkfiSrjm+bqDwkM+LcTmIUfwglySRQjCbXv99nO5GYp7RNYTVXHVKxBzJRt6dFBJCmCKaqyuhvIo8DZ1APYWmFxuFQ58+WU/rHkcWc5r9YwspNMhJp3drBXLCtZgl5qQt42UL6d1gbODCMrVZrWgWH9KhuXQ/DWGGbHc=,iv:8/BZiEdqBzUGbRZDO82uQpKLdVbjbsNFplrPx/Kb0y0=,tag:5YP0+LQvb2t9eKbYhX0kvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
