apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:6Ss9nMoWfFPaV9k4MSVHG5uUMNQEYml0DtfOAw+r0EpXVw4kE0DqtAfbyia1P2L+AaO3aEsZJdJjCYAqtm36Ev9HZHr6GAM3VVdDvuxUvhwiTeXFLIdQjCSV0zZ64vCi75vRSgOqGmKV5tRPyD3DDOg86zQZKbzeafMMRgBDoJlbm/54gF0O/KSpXLptc1ulwSRIjK2AOGC8i3XVjwH8diV5W3RhegiEvL8BgJYahYtBpYF6,iv:SO2b991HhT9Ki1aG4jQfAa+XuYx3hDFtSKxL6npiYiE=,tag:5TBrrm4XWQyUEEfkEin0Lw==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SGMxdmxXc1VUOFZ2Qm5m
        T3gwYS83Vkthdm9YVzNacER4NzE4eDZDdHhVCjZpWXV6UzR0ZlNHWC9SeW1lRXlK
        U3dsUzMzSjQwNVFLVEdkcFVJWXVkOEUKLS0tICthaGJOWDh5aUFpTkt0Q05wOTFh
        V29kOGNZbFFRVkdacEF2ZXl2QTNmL0EKpVskx6bEwvf7/kGzME4dmQKX6s9WUJ1L
        rRknuUVJqWad0eJC8CAMi8UnK/Oill7+muL2ymHmROcW/IHdlUUtyg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T13:28:49Z"
  mac: ENC[AES256_GCM,data:XG9b8+4RmK8ih51LjdwKHScnADRvhBhkdyo6+0fntIFqhWybc4cuUWXyLFeBRkk9qZJa3cpDJ/XDquEQSfBDU8+Jm+NfWBpjvmDJ8YeFhNrdSv0M0gADcq60/J24TBYzHJXICokL5t3VYDkjxGiYpk79yWDr1S5BojkSGkPExgg=,iv:uxI7ewDyWl7zuy+PjCbySmTxRWk/SjtEw5B0yebae9s=,tag:x0df17NO0Av9BVCpsaorRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
