---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
components:
  - ../../components/sops
  - ../../components/alerts
resources:
  - ./namespace.yaml
  - ./kanidm/ks.yaml
configMapGenerator:
  - name: kanidm-configmap
    files:
      - server.toml=./resources/server.toml
