# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_DNS_HOST: ENC[AES256_GCM,data:kqVcK3VhU118yXh7QU5Zdw==,iv:Y+2YnP586+bWofSkftsw0nlWeQ+gaENzg6hBqIVpY0Y=,tag:Ag9qtkiX8L8TCFgCo8qRrw==,type:str]
  UNIFI_DNS_API_KEY: ENC[AES256_GCM,data:HxPglZRhsqaSPcYDTHL7YSgHxZ1CLm0E5epGqZWguB0=,iv:F89PCReg8I8zORoTzI5Uk2BwWdwwW3aaPg0IYliuPcI=,tag:l7DUJ9z7+9suEGWAEsXJAQ==,type:str]
  UNIFI_DNS_DOMAIN_FILTER: ENC[AES256_GCM,data:Rkmn7HQHglD1,iv:1+WGS4SV4HdQ5M2ww6/z9626CZxvbORG9rlStp/uaPI=,tag:TjKOR1fatEbJLSA8EzkkSg==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuL2FZc0NoRHQzei9HdlNp
        WktnTkVxQUZmU3p5RjN6ZWVHTytURmIvY3lBCkQrQjZaL0VraTNudHpTNCtLNGxo
        dGNnMkhnS3lkaFd1bEk3ZnVyTEp0bmsKLS0tIDdFS0czL3c1c3JBZEtMMDNNMklD
        RHRIR0h3YmZCWlUzNlZjeStOclNpQncKD2da3SgdTg1bV503bG8QntKsL1ayeoKz
        MzMtvrejjX/PCTyzhWYDQSWDBuPonOecXeb3hj2IkTfrtwkaBad1/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T20:31:04Z"
  mac: ENC[AES256_GCM,data:FYUgxhFZDma8Xr2vNeU8u02/nhP0OpgNPWt0s1KJ7FE0MKVBaxCnyqpnQqfrSdetKYfQ37JLd+50QSyPMl0tI/dH+t96QX/32bUfvcR/GPTTQohJWJ8ZMBe3wTn7pQOVHY4fnYC7ppomGN2Pxv9DG3wbZ6tHICLrjhb31zdNbxo=,iv:rJVYNcyPzzdot8PdSc+U1eBLnd7WkvLYaG10AMiMd/Q=,tag:RrIN+AIJhk/CK7chY55/bQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
