# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_DNS_HOST: ENC[AES256_GCM,data:bdU6zh6HZUskyk3ycNU7+Q==,iv:NGNEWj5BtWs5J/qRbwQbzYb/NKgQVfOGALG5Bd+fxFI=,tag:mgQTFC/JAeneqX8pmlbtDQ==,type:str]
  UNIFI_DNS_API_KEY: ENC[AES256_GCM,data:CYJfny5KtWnt19IeqZCVtMnOeUZRYaD4R+RKYZ3Nxpg=,iv:EFeMD89VMrdwVfw4oF7/0X1Xu7TWPzBzemLkMWvVXW4=,tag:AKznoqBCXsCxeEy7ZXE85A==,type:str]
  UNIFI_DNS_DOMAIN_FILTER: ENC[AES256_GCM,data:0rGFfOKJfxON,iv:mvnwFGRrDAnse0U+2csJyjHqUpBXivDXhnrEIpWCLcU=,tag:5i9Hf2JYH82Gp8R57egezQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRll3OGMwZmQ5K3RyRlA2
        enlWaG1Oc1JiVXN6SzdnKzRsWk9ZOW16d2pFCnVoTWdpS2RUcTVLTUJrdSsyNzM1
        MGRnS1Q0bkNiVEVkREt3dUZiTjU3djgKLS0tIEVqbHM3TzNGcW5qMHJTSUdTL2ln
        WXNHeGlOaWc5SGR1eStXT3FFWk5uT2sKHanr4he1HEICE7iKa6rGkqazzVhkL85K
        jITY2aVctu/YElkpJBQzEkLKuvaOHxxfJL3bDvPpBf3jWZ41BAGcuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T13:28:50Z"
  mac: ENC[AES256_GCM,data:aAFz1VbHrS/+EeXRXS3xh6uq+6lOpB2YAT0iaqZjqNn5OY5bm+uGf2mlurcqMmAw93sNFyNHGAxz1BOs3/mkgR6Zd8PKfXBf0ZllFSlJFyZgytmM/Hu1FgB358TBx1WncwlnJ8bAe8iYpdEuR+a5MGo5KaNgphQfY3NmcH1symE=,iv:aEaiHJafXO3Cet4yZ5I9gMHfpQ3ZyA586c792Y2v6cs=,tag:3SOlXrkgvjg4Coiv7gHRRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
