# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_DNS_HOST: ENC[AES256_GCM,data:OjDHf8pzWu9EH/NN3gvD4w==,iv:2d0qh4e6fwDsr9fwasg7LuRpHtgCfT7qIQ3IZuYh55w=,tag:YzkFJKLAG5k+SmpyesqaWA==,type:str]
  UNIFI_DNS_API_KEY: ENC[AES256_GCM,data:+hpNL4V43qtoAVMPrs4UtgWQRNIItNUxLtyl162DZ6w=,iv:rgvPjw9xUqSHXG2BjU1nzAA3ZU0WBmGo/Xq6CUWAknk=,tag:GxEgBUWndm9RSBPaN6+dzA==,type:str]
  UNIFI_DNS_DOMAIN_FILTER: ENC[AES256_GCM,data:wCiilmvLr45V,iv:4L9JyV0D3CnnJQrBN0pIzZdmSGNQnmwPwOAxYSoVLsk=,tag:16/2CpU5FAPcqp0dXtmoSg==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSnJmeWloaEE0Z1NZSExz
        aW5vZU9IWVM2NGZudWhnU21BZHpGRkVaRUdnCjJ1bXpKbEQvcTQzWk1WUVZ4dndy
        Y0tvWWFoV2dpRzVYVFB0SlluYlgzODAKLS0tIGJLVCtEanRZNEEvZStWRnQrYzRV
        WnJPSCtEMUJZK2RidUFGOCtJek1yNTQKQfP8x0CwFbAoMzuTwlJqxvM+sfTdAxPL
        UJVG/CrxdE00xuwobaTnpFZoXPhAvKYcLFDufNjpnv+/YlqqCujxIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T14:28:49Z"
  mac: ENC[AES256_GCM,data:KMRRDzleEy+C+orzKQsfH38hdTkfmSkJEmz5XM0v6ZCZ01UfXiG+rpE9avB14NrJiPEkY93pPzJBXSDN3t56MDgs6Pbay/amIaRbFLjiNqOHbyCU0OyXgldKdfwA1Uv4VaEg6WAfG6AKynzbmw2apyHviHKzytrIFwttWS2udys=,iv:Kk7zWF5mjIdgq29iswUmX4q1ftm4tbH7vJLmKhIH0ig=,tag:TZeHH0cRN/kb5H8xSQdkEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
