# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_DNS_HOST: ENC[AES256_GCM,data:L8P/bcgWWY959vRInrbZcQ==,iv:KJIqTx5HYfB2utzp2EjI9mLYw/MPEadsPV9M62FHHjY=,tag:3Y6KCbPdoedZSwfa3bGkGQ==,type:str]
  UNIFI_DNS_API_KEY: ENC[AES256_GCM,data:5mgexkZ3seWSMzm3RxQI76MjR8TTC3jdLbegWEDFrFs=,iv:sdRy9zSTW2axwlnZjdUM4k75DFOVLB+ghSVOiTnEr+I=,tag:NRTEkvHT5soURTxPwGgF7A==,type:str]
  UNIFI_DNS_DOMAIN_FILTER: ENC[AES256_GCM,data:2hCb74WNmJbC,iv:Sxei/sl3s9I+rtC8dfjLFBCJwZSj3nonezdo4w+CJTM=,tag:8/me1vUNkyikpFnok/9mRw==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2d3huK3JQR043aWY5Y3Ji
        TnV1YmxHcDljQUlhNXg0ZTBzUkxrSDJockYwCmFkNUJ5ZDlCMkNYV2RXTE5iUGdL
        ZUVlek1EdlZkRjRLa0lETkk2bHhVVjgKLS0tIENwSFFCV0o0WG9iU3E5SUtiWkJM
        MUN0N2ozYVNZckwxWjNPVWk0S3pvM0kKcaDb7CBlGxYpHftlnBV7v4Oba0aQaWoy
        t3tKmQ1jIanpVc3lb4Qm4SFC41DARRbMULxzxzuiUTfUehxkrDC5qw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T13:37:40Z"
  mac: ENC[AES256_GCM,data:QgSxRfZIha+629+9i1dvbUD3mvi0RqACbPRdAJbf/HmYUNWVwlgq2t2sC9ShvpcUORj3Nv43tKw7ZeFXx0bIKKSmrQgst6Z05FX4i4wH8csyuQrXg2lFuDYqQy3XA1ZfEPJLLIvNzoUv5RpQ0qHl+fQwzZyDBoAoRVvzmTaTsrE=,iv:DZdMMie065/hKD87DVbek7B+fd7AtiGo8Ztw96fgTo8=,tag:aR/BTn7ZfApPeRNgzRrjjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
