# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_DNS_HOST: ENC[AES256_GCM,data:j4xj6qEgHR+2zyBd2AELcg==,iv:d+HHFw2cYs4RMwhF5HPI8jbfyJM+7XYdXENpINeZCsI=,tag:GfbH52SWSuBnko8u3Yj25w==,type:str]
  UNIFI_DNS_API_KEY: ENC[AES256_GCM,data:pTGu1DhN3VOpMJeiMuFvkfcy0rkBOx23YgnEPH5cBe0=,iv:KXeUtTvICAIpswEjscy4qtVurZIJVNFTdxNVY0FrEng=,tag:We6ouvh95xyL08i1+DyhOA==,type:str]
  UNIFI_DNS_DOMAIN_FILTER: ENC[AES256_GCM,data:waux/45h9x6/,iv:FtDokgtJsmJICpd5JPF+7CIcPt5KluxeTWiNrtyT+UA=,tag:2ZK5gBkeRmtoPTmuI9/k1A==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeEE4S2ErTVg0VmdvZHhD
        WjdXZWJDRGUwK1hmTkR2eElUNlgwZEx2bGtBCnhxY0dhdnVoSXc1V1NBOHQvZTlh
        STM1dmxxOHVBZHFPbTF0aWxtNUhqYlEKLS0tIDVvbnVhUGJNaDlObG9hR3c0WEJm
        dG9zdFl6dHR3dVFxcDZZVTROWkk4RmsKxYI+fBEQRmeSrL7uHAOzGXOCuA//aPO7
        l4ba9R8GQlRN2YWGz0vbo9qC0Z36/cAZhpobBkRI5jHX83x1ZJtZag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T15:24:48Z"
  mac: ENC[AES256_GCM,data:vD9wA8Y6m+mubw+97r1Ylp94KLx6S7VNsvJgPs+p/nzU2EE3t3rZEbJhDYBDItUhS0MoanxPDe2nnx5BoJrJNqBqSta+JeOhuNVOVdKHY5xXI698axP796s3sFitcq92GhbHS4DGM7QG4ChlLo9775aRiY2o9JxbWHSZhfHE8qo=,iv:y6V/7xpnOayIO327+jF9kT16NxQJJgXCYGf8PkrCBK0=,tag:p8zrfG6suNHYHzWpFZdasg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
