# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_DNS_HOST: ENC[AES256_GCM,data:xUcgmfR4W0c2cjeO5lggyQ==,iv:CX/NhJrOYzxyO5zZ/FGo+zJAHefNQT1kkQxeMWHKwPE=,tag:PMPOjIXJQYE19EKUTn4oTA==,type:str]
  UNIFI_DNS_API_KEY: ENC[AES256_GCM,data:6SWhkW4qVUyHb8IHHtFbE4oq8SPU44PIRz4eXP4IGsY=,iv:zuWT+/IaBuK3Ravo0dGmcypSZXcMg1tTeHOOqguHLlI=,tag:5vglfyIJ+YdcfI4+xs9vvQ==,type:str]
  UNIFI_DNS_DOMAIN_FILTER: ENC[AES256_GCM,data:BCdex2+wJ9NS,iv:/AucY8VbN1ssJXqMe70CRmfnwWpcc1rcZamG8EXLV3k=,tag:KIMHOUKuvhkl5MMNQNCcYQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTzIwVXc3LytBOWlrRWpR
        Nmw4WjdaWHBhNFpzRlhzMC9qK014RWxIRHhnCnpPaXhOVUFFZmx4K2NVWSsvVGps
        d24vMHZaRVU2NjhUeDRWbVZRZUZIL3MKLS0tIGVidlJsbU9aWDlNb29TdlpwV24x
        ZWhjaFlPREc5cWpCMEdaRlNNRVFJczQK4kZmvCHrt4HOefyYpSdEYiArInUkPEPR
        x0lQ6cr1wzX+MrEjg+O/iqDfXq8uEpa6MwkfnUpnO9Y/1PJq7GK+hQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:54:38Z"
  mac: ENC[AES256_GCM,data:Ytbne3HIUSnti/Ytbcppo7rJoEUyuka0y2gSrUWIhyZkEgb54aaOQA8+WpGuDE7jwR/0gksDbRlRYx3Pn3eK9O0Z6BGLAT3ZdoGJDTlabrxOv9PCRvox8uKapHBVNJuH8OxFo7fbhmFVrK2jeF6z7ywa0M+uDuhGeFmLo2s6z8g=,iv:09FmY5BlvZS4qK7itxnv52N0pustSPvsUnADRHPc9cU=,tag:zIXUm3RTg/r0Ntux8SsdEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
