# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_DNS_HOST: ENC[AES256_GCM,data:wSwYKQPiMKPjpdz8bdsbWw==,iv:xCWFpS1YjqUgP47V/zC8onXiZms4QdUIKMQABB1j8NM=,tag:Yrty2b8mQKIfGv4Eh8IYqA==,type:str]
  UNIFI_DNS_API_KEY: ENC[AES256_GCM,data:x5XAYvgP5ITDooKaM77kQHgYhkhPUPHPByMyDM55Kfs=,iv:dWjiizHlqNCZ3p7QYNJrfUo4in6WcFgUbsSjK5yFscc=,tag:zXBGTZ3IGmoXobX8gxURcQ==,type:str]
  UNIFI_DNS_DOMAIN_FILTER: ENC[AES256_GCM,data:HDzjTzAG2lWC,iv:YV25FAtc4fuL4wXSZVO0XWuF0I/qKDeYew0R5wGyjGk=,tag:iJnfmpRYQybPVFYeFb4dNw==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZEZRQlYycG1BaThENm4x
        WWJxUmNRT3lFeWt4R1FUVU51Tkt1Q09XTHhFCjRxN3FVSEpkdk10dmRleDE2QUM0
        S0YxelVPWTZDelhET0ZpRW0yLzF4YzAKLS0tIDNrNXRNa2xIS0hkTTg4dVpYUytz
        Uk5tKzBkTkZmelllQzV6WkhmbERUTE0Ki/dcJQlcgH8crSWgoSjHyBvquZJXueDI
        pHcgokopgVjFUVSKmwVAsOWczXVn5LN04JBuH5YKkcVv9EiRwM7HKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T20:48:26Z"
  mac: ENC[AES256_GCM,data:GxuVHUwJBRSZbbwL4+JHeXS72bGRAoKaE2iqOYZTJZcyvX75SVvWq1q6S+N9Qg7stRtCd8eVrFUufs5DgOMXGPb5C83IkgYob4/Ao70RE+ISQ81BbIFg3rIKe8zHPAgGUWCp4YE6TY2ZMtfwwjNjvHwd7MdQY5oeG1kmmTvLtUA=,iv:HpMyP6LwckvhL/Klhh4vT3GNmyIRB8pXpO4AdRTWjLY=,tag:PxUpOPosfxTlwh1ZliygXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
