# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unifi-dns-secret
stringData:
  UNIFI_DNS_HOST: ENC[AES256_GCM,data:rMkCOdg41HbT6ddbzEYClw==,iv:McNDpjw00M700bBp1AiBVcD0Nwk1CUzkrIyob3LDazc=,tag:a/5k5RnpzePO2VshfPKFag==,type:str]
  UNIFI_DNS_API_KEY: ENC[AES256_GCM,data:G7gNokRSbdN1N2Tmm53cMRv4Pzi+TxGV+ok6L74K/yo=,iv:HFhQSc2AeG9X3H2c39IvJ22zFJBuGBA0Gh3POf7jtGU=,tag:vy17vYXnnlLEfnVvw6q+DQ==,type:str]
  UNIFI_DNS_DOMAIN_FILTER: ENC[AES256_GCM,data:uwmcXKXVnFZ9,iv:mkFpLgsh7a3nrOTERZZMLVsTbtFdLJbdBBTlacprnAk=,tag:6VeLd4TYE879e2Fnv7F1qg==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNjNjNEpDdG92a2gxV1NT
        UUQyNFpHRm9TbWx5Wm9zUStmTzhEUXFGQlNzCmRTMkpMY3dBUGlrQkhCMjg3YlM4
        Um5rNi9mS1QvNmF4aE5Va2xYekx1NUEKLS0tIG40cXB3RDUyS29pbEtuZzlUVThO
        bm1xYWozOXMxWEJHOGJZcG1hOWplaFUKw7CZiwV3SRwPaiMYMNBfdVie+qu7Bwa0
        jEqcnJWsRrJdhefr4CzJoqERY3E3FND5dByAOv0cMzAwe9h+7CFECg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:17:05Z"
  mac: ENC[AES256_GCM,data:USeuVCs2hq72zMpyi7RRyXdJ7kPI8W7EL7IVPRCNG/oerIoZV31rdTqyn9IkIxUAxnFaUR8NlxJVvnQrko+CZlaihMdahHPpx37U6AoagTcRzXN7LwEzTLjm12bpVnloEW+eK7Mku3T3J4kirjsgCl7rKNBv4PRPWr/DDAby7KQ=,iv:eno6t6lB7FeYjnUg+DWzsw6uFxoHPWOrHpDmORPfMVU=,tag:QSx7DUVdNQ3K3FOwJNnWBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
