---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo-runner
  interval: 1h
  values:
    controllers:
      forgejo-runner:
        replicas: 3
        type: statefulset
        podDisruptionBudget:
          minAvailable: 2
        annotations:
          reloader.stakater.com/auto: "true"
        statefulset:
          volumeClaimTemplates:
            - name: data
              globalMounts:
                - path: /data
              accessMode: "ReadWriteOnce"
              size: 10Gi

        initContainers:
          register:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 12.6.4@sha256:2b65f3ba4345026d66de34dc8eddabb7b0f64c0e14905193ae81746f2728caa0
            command:
              - "sh"
              - "-c"
              - >
                if [ ! -f /data/.runner ]; then
                  echo "Registering runner...";
                  forgejo-runner register --no-interactive \
                    --token $(RUNNER_TOKEN) \
                    --name $(RUNNER_NAME) \
                    --instance $(FORGEJO_INSTANCE_URL) \
                    --labels "$(LABELS)";
                else
                  echo "Runner already registered, skipping.";
                fi
            env:
              - name: LABELS
                value: "ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-latest"
              - name: RUNNER_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
        containers:
          daemon:
            image:
              repository: docker
              tag: 29.2.0-dind-rootless@sha256:e2256cccf0a81babdf6b0715edc84299976eea749dc373de1d4c4b98f38be576
            securityContext:
              privileged: true
            env:
              - name: DOCKER_TLS_CERTDIR
                value: /certs
          app:
            image:
              repository: code.forgejo.org/forgejo/runner
              tag: 12.6.4@sha256:2b65f3ba4345026d66de34dc8eddabb7b0f64c0e14905193ae81746f2728caa0
            command:
              - "sh"
              - "-c"
              - "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; forgejo-runner --config /config/config.yaml daemon"
            env:
              - name: DOCKER_HOST
                value: tcp://localhost:2376
              - name: DOCKER_CERT_PATH
                value: /certs/client
              - name: DOCKER_TLS_VERIFY
                value: "1"
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: forgejo-runner
        ports:
          http:
            port: 45315

    persistence:
      config:
        type: configMap
        name: forgejo-runner-configmap
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
            readOnly: true

      certs:
        type: emptyDir
      cache:
        type: emptyDir
