---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./angelnu.yaml
  - ./authentik-charts.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./crossplane.yaml
  - ./crunchydata.yaml
  - ./csi-driver-nfs.yaml
  - ./emqx.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./k8tz.yaml
  - ./kubernetes-sigs-descheduler.yaml
  - ./kubernetes-sigs-metrics-server.yaml
  - ./kubernetes-sigs-nfd.yaml
  - ./kyverno.yaml
  - ./longhorn.yaml
  - ./mariadb-operator.yaml
  - ./nfs-subdir-external-provisioner-charts.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./stevehipwell.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-sigs-external-dns.yaml
