apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:QJD1ydKuqdQEVOBZfdi4mKy7JPfsnuIAT9HhAcuFUdlnzU/AKJtS7w==,iv:DmGEE1wkNJh7SGYl6jyQhjJN7nct5EaHoK2jSO4B7dw=,tag:HTNRY1ItIgBds9yls2u/uQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWU5oQ0R5OHpYeVBVZHpO
        VkRmKzMvWlRrSi9UOEhYZ3dyalA1Tjh6VFhjCi9zNGRTMXdoQ2crWHJkYTFOaDRh
        Vmozd1JmMCtHNGtxR3ovY2o1em5CUGsKLS0tIFJiVXNxbjhrdGZUcnB6QTNyTEtQ
        MDVjK3dhcUNLL2NBZlhWemo3NzNzT1kKwQw5Sb4Tc+d38YDxO0qOD5wPlEASZhjS
        XPVxbHStw79pTXNRqKvl+67pMKneriVqHWrxqVsIzRa8p5gMh5sC1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T15:24:48Z"
  mac: ENC[AES256_GCM,data:qmIgH4uupZwnsZSSF6jR9z8RMIYzN/CQi4JOMw3r8tC/tlQX1w1hCSXbMD3HhKNRKUGIGD+KvvF1yB/Zfh7D5ckW99zoTF84G0iZZoLXudClA/JDL1ogq5txnEOGFuTeJSa2xuXqeAlBacgYYusyn05xoIuRIra3sX7ZiyKDigw=,iv:zS275tTI3upk/Bm/9Ruo30XmXDr8IsCoZtsEWU5ybxk=,tag:MoqLi8BpMYQaApbNGKGLgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
