apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:+KBN82QMl5gVqaoAuC6HcGs0XVbSyTfCNkwhIPz3kASvs7DsX0sHNQ==,iv:tS7mlY44FTgXgv0UfPo0K/ZxAx3Fbd1cS/JrKwF+Xqs=,tag:rlA8NXQIOebLA4bJO/wQXw==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrN1E2UmZVcEhYem5WNTNo
        ZEsyMEhVa2JRclYxK2dZSTZ3NXhYZzZ6TlE4Cnd2eC9WcElFbGxVekFzUktiVi9z
        cEgxaGUyMlJRZmpBWkVRZ2E0ZlBYT2cKLS0tIFFtMWU4SlFDdFp2Q0tzY0FjWEhr
        bXRGS0lhRFUrWW5SeUJpYTEvTjFlb0EKLdceBdeulm3mCzbc9qjPpPfyNjHjMgK2
        GiMA1Hz52KTVpWl7G3zQn2DxyfTTbe7cyzISNbMAgM0kPRvGPF2e+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:17:05Z"
  mac: ENC[AES256_GCM,data:ljekdqEgQI1W4Elzz5EYFqHZ8IbqMPExrICcwbaoQHTTul4e41wpQT4IxUCZHUIchg/DGz8EMTHoCYgRlJvRGUDIJrbkgz0Iyqc8kZFO2TCVKsnD3Mmpo5xfNp8XK3dQ6mUy/yTxfKLZXmwKT5+J2pXYp4QlWFX0xwmy17156gk=,iv:W2fPX10VA8BL2qvu4tc82k327u4DIIKu0EfB5yLfafU=,tag:azfO9mmcp9oHGHDUiWBjXA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
