apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Ro5EcioQ7XsE8+emUBWpNA+qAZG+TMujomnlfn+9ZJpnshNE899HFw==,iv:bYEfzL1bZFKnGNtZa2gUJ1AyW4LRD4mdOqJ6/WJRPX4=,tag:fWOQhp3xBX7+Pms/PO5BUg==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbFdhd3N1QndkNjZYMGxO
        cy9SNldQMHl0WnJDWFNaSmsyRWRmdWY2U1RFCnFCajc2c2sySUgzVXhRMmJ3WkRz
        YzNvTEFjUTZ1bVNaWnJ5SW5VMEc1ZUUKLS0tIFN5NmgxMWs4bit5QXZLVnRQM2tG
        MFpSL2t5MGxYcWV2cjIyN3hDQ0JzaEEKl9QjqWsvfxhtHCeJSQwayS2MQeNqABwR
        vIQf5jKWSctkhkBeeJnPLFsk5rWAjvf/25Fnd7IkPzhp+SulJ5WJYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T20:48:26Z"
  mac: ENC[AES256_GCM,data:+IhyGM2be9osDShwnAnMHsjEaNrtT30KkZQJDQlXAXBIDStJ97U6DYfG4R3eePP0VQF9GiHtSkCPXZQ2I8W+oJos23pgS1qMkToZl8a455jAjFMy3G/+KSxc6026xKpbEMGx8848iL8IqzofZm1hNbhwcvppYN5o3AVVqkKLP4A=,iv:62SWENBYD+2q6Oq4goKFvqVAlohMZQAZ9/+qiUVcyLs=,tag:qbWzk8JsLctvJQFb4xRsww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
