apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ISvU3VOB8K3HI+zjbrTYgTjbbzxHE6G+h4pO3HOmdiGDsA9Z60kMyw==,iv:NHEn6PpxcVJSUi/LN4hI9SsDM2pUtoB00bX2ptkCo1w=,tag:A5qg3nKXD7b06e0+cKkbpQ==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUUllTWhGVENpT2NjTXA1
        R1ljNkdRK0dHMUNaWlNrYlkrci9DMHRrNGlvCmVOa1Q0Vyt6eDYvT1ZpM1NFTUhn
        MURvbG0reFNBcVhxOEhRbHo5MDFIMFUKLS0tIGpUNFdrVHRuTzRJVkhhNmRQc3ZE
        bjFKcWtST2cxaFMySVUweHQrRFNmMlEKwqQdth/G5vx5PXwI3l/SbHCJf3FVBipH
        lueRR8rBIzStCrRvFQefotYUYLWTOpZkshYkXy5/8O5pdaY6a9fgHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T13:28:49Z"
  mac: ENC[AES256_GCM,data:7DVYqdE3fDDl3u/bEiYA6fpgutIJemObttq14QXdkuC+HS+nDDEuhZcHbn+UpGNJz0eMPc6lfaIEtsNTwuMHq8us937ygUWf0YHViUn1yM6dcTC1JYOLls8zPHpO8NCvNdaTfg+otrzuOKIBIJMQexhsn3PSAybfOlLGhf3vQpM=,iv:xrBJ88vpR1X17VqT8dXJ4RmgZtE4ETIjebTz5ZRMXsc=,tag:sjXLSjnV+cXJIR3VJ+fVBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
