apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:pjTxsNCAObL/n+Ef7RO7FnrMZ0s5zfa7X2agj4ZymWfY5fTE7ZM2uQ==,iv:e64lyaEwtjoEz6XY3m76Ig38D3JYMO9Ps0uVS+ffxSU=,tag:c97fNnuDon4M55e87DT8VA==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTDBWb3VJeWNwN0xoK0hE
        RGE1aTQxTUxqM3IvQ1NSZFk5Y3BnR1RWS244CldZVEpzcU53T3A1UDJHVjg0MG9M
        VlI2L1Z6cGc4S1dVd1REd2ZDeVpCTzgKLS0tIGdvb2R4ZVcrMFIwSCtkUW5ieHg1
        SmM4Nk1SRUEvMTZCbXhZS0pmQ0Q3dzQKma8v5TmQnfxz9rXOh4Q5DIIAOzvr87ua
        LUGblLLeDK9THc3tA+HjvOg17TMZQGj05MxUoaseSJIOhyqwixhU7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T13:37:40Z"
  mac: ENC[AES256_GCM,data:MTEfLgHwJaMi3w+U74vXgLvBzics4JPoivDuVb03iPSnVBZHuRT1kk+Jx50aUjI6wiSMoIVXyxrthpoTkJ6m5j/TN6iJ4tC1izid7DSNh56lTFnxhtmsUyg0hLzj9aHE8elnjte0IW+1wAOQtxLNfQV4rO1HAHViC+N8a+k6O6Q=,iv:jCG5qa+/II2PRlJ7UYWOq+2sS1PC+ywOTO1FHt36YOY=,tag:XaAz1MYHcuJFB20FDIpnaQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
