apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:LppXzx1uw+N1urJ07Oitck27tGIl62n6FkU87EYSTieGbOElDB8orQ==,iv:NooKSI24IVYsdx2S/mm4++yvnZu0vXSTMlx7ANYMwgw=,tag:fWfEXmjGYGLQ+btt8WhwVw==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcnpUYXNxc05vTGlpaDJt
        MjJaNktZS0VXWW0zVzMrK3NhNmN0b2RtS21BCndLdTMvOFNrOHFtRGdUcDkwTHQw
        T1FiUXltMjZ6OEdVT3lPUEd4bWF0VGcKLS0tIGljZEVvaGg5ajJzNEpuMXg4YWVh
        cG90bHEzbDlzc3VNRi9kbC9iTytzT2cKAJUTHgBmk2SoxOrr1Xy0JSQwMeimGjBO
        PidBneDigJpuhaMrs6bs8F4E/Iv5aS2wE+YzKf21Rr32ted3niRmkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T19:54:38Z"
  mac: ENC[AES256_GCM,data:jBRgWjYsuSAzhJK/tYv5QRT4BxkQKaKdlr1/E6hvSf7plphIrauSztJ6xIV5wOazNzHL6swz/w2LDStoDu3h8yxJLLbbluj8zVMIYCfuFipygMJwE9JpdwfhcABlQ0rRt5yP/yCOBi9hAU2XWIlv+R041s4HLS/I8QHZ/KrgGnY=,iv:DUjgjZrYCpgHfBi+8V7INcgECXmsJwG2CQ408xPm3L4=,tag:FT6JRRYPmGZIL1j7j6M+9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
