apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:sQns/TPNlfkxMs8KxhI4dJO9ZF1irsOgQKCY3yDiq5eWFDA3M6xsKQ==,iv:lmMZWqGh1NpLldyWiDezkDP6WCfkEFQHxeaZeEloim4=,tag:mFhqPy7v62RjkyO05C1AOw==,type:str]
sops:
  age:
    - recipient: age10x2a6rhd5v9kd5w4cn9jemdxch7ecsltw3mpynx4gttcdpsqhumqtkh6kf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZjF2OXNZc2JPSUQ5QVNk
        YWdRaDNjejZ4bEc0b1FYazd1dkZuYXloZ1drCm1TK0prTlVvVWRlYVZjMi9RUUdL
        S3lDSnNEdkFSWFZjYTBOK1NLZHIvQmsKLS0tIHk3amh5RnlieUJ6NzA5MDBjZE1N
        UjV3M2dxMHFIcE9VdkJNL0FsTlZsaWMKckiR0yztCO3MkbvoMpe4cbjeBFo8tf+3
        UMDF7//KrwMtGToDVaODuG84QTEgFbJAa9RI9kHZX93I563I4g87AA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T14:28:49Z"
  mac: ENC[AES256_GCM,data:4j2KRRo9DDpWW79vamcf7eGTOj2Ai9wKMcMSSHH0CFgdwLqLH6qU2qE+MGOK4zwBDgeahXk0Clei4WaXha/aBBTyZixXsdQyE4CmlOReRYt8gz3HbLU5t+dTlpELVSIwn0r/cLdnmGebLoyag/s1uEUxY9YaZpbo2LbhnE6KJDo=,iv:92k2S3j3ldExfzWXjGjnxApmTmee4oRqOb0qdphYvOI=,tag:SXnuzF1Eg9voVdTONX2JOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
