---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ../../../../../shared/templates/volsync
  #- ../../../../../shared/templates/gatus/guarded
configMapGenerator:
  - name: pgadmin-servers-json
    files:
      - resources/servers.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
metadata:
  namespace: database
