---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name ${APP}-tls
spec:
  dnsNames:
    - idm.${SECRET_DOMAIN}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    #size: 384
    size: 256
  secretName: *name
  usages:
    - digital signature
    - key encipherment
