---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kanidm-tools
spec:
  chartRef:
    kind: OCIRepository
    name: kanidm-tools
  interval: 1h
  values:
    controllers:
      kanidm-tools:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: kanidm/tools
              tag: 1.9.0@sha256:cb61c6bd71d5630dfcc05ed32c59fae0667f76a70bc9428dbdd46a267cf74884
            env:
              TZ: Europe/London
            command:
              - /bin/sh
            args:
              - -c
              - |
                echo "Kanidm tools toolbox pod starting..."
                # trap SIGTERM/SIGINT so K8s can stop cleanly
                trap 'exit 0' TERM INT
                while :; do
                  sleep 3600
                done
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 499
        fsGroup: 499
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        type: configMap
        name: kanidm-tools-configmap
        advancedMounts:
          kanidm-tools:
            app:
              - path: /data/config
                subPath: config
                readOnly: true
