---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kanidm-tools
spec:
  chartRef:
    kind: OCIRepository
    name: kanidm-tools
  interval: 1h
  values:
    controllers:
      kanidm-tools:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: kanidm/tools
              tag: 1.8.3@sha256:5eeb5acba318c3a78e5fcc08bbd1efd016c3226789815f5c112477e0ae6a513f
            env:
              TZ: Europe/London
            command:
              - /bin/sh
